namespace JobBoard.Domain.Enums
{
    public enum Stack
    {
        JavaScript,
        PHP,
        Typescript,
        Csharp,
        Java,
        Python,
        HTML,
        Ruby,
        Scala,
        C,
        ManualTest,
        AutomatTest,
        DevOps,
        UIUX,
        PM,
        Scrum,
        Data,
        Security,
        Architecture,
        Mobile,
        Go,
        Rust,
        Analytics,
        Admin,
        GameDev,
        ERP,
        Other
    }
}
